command:
  - ${args_no_hyphens}

program: src/scripts/model/train.py
method: bayes
metric:
  name: val_loss
  goal: minimize

parameters:
  trainer.optim.lr:
    min: 0.00001
    max: 0.0001
  trainer.gradient_clip_value:
    min: 1.0
    max: 10.0
