_target_: 'src.pl_modules.generative_pl_module.GenerativePLModule'
generative_model:
  _target_: 'src.pl_modules.generative_models.bart.BartGenerativeModel'
  bart_model: 'facebook/bart-large'
  dropout: 0.1
  label_smoothing: 0.1  # 0.0 for non label smoothing